package entity;
// Generated 14 avr. 2019 16:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Apprenant generated by hbm2java
 */
public class Apprenant  implements java.io.Serializable {


     private int id;
     private Compte compte;
     private String nom;
     private String email;
     private Set modules = new HashSet(0);
     private Set formations = new HashSet(0);

    public Apprenant() {
    }

	
    public Apprenant(int id, Compte compte, String nom, String email) {
        this.id = id;
        this.compte = compte;
        this.nom = nom;
        this.email = email;
    }
    public Apprenant(int id, Compte compte, String nom, String email, Set formations) {
       this.id = id;
       this.compte = compte;
       this.nom = nom;
       this.email = email;
       this.formations = formations;
    }
     public Apprenant(int id, Compte compte, String nom, String email, Set formations,Set modules) {
       this.id = id;
       this.compte = compte;
       this.nom = nom;
       this.email = email;
       this.formations = formations;
       this.modules=modules;
    }

   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compte getCompte() {
        return this.compte;
    }
    
    public void setCompte(Compte compte) {
        this.compte = compte;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }
    public Set getFormations() {
        return this.formations;
    }
    
    public void setFormations(Set formations) {
        this.formations = formations;
    }




}


