package entity;
// Generated 14 avr. 2019 16:29:45 by Hibernate Tools 4.3.1



/**
 * Chapitre generated by hbm2java
 */
public class Chapitre  implements java.io.Serializable {


     private int idhapitre;
     private Module module;
     private String titre;
     private String description;

    public Chapitre() {
    }

    public Chapitre(int idhapitre, Module module, String titre, String description) {
       this.idhapitre = idhapitre;
       this.module = module;
       this.titre = titre;
       this.description = description;
    }
   
    public int getIdhapitre() {
        return this.idhapitre;
    }
    
    public void setIdhapitre(int idhapitre) {
        this.idhapitre = idhapitre;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


