package entity;
// Generated 14 avr. 2019 16:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private int id;
     private String login;
     private String motdepasse;
     private Set formateurs = new HashSet(0);
     private Set apprenants = new HashSet(0);

    public Compte() {
    }

	
    public Compte(int id, String login, String motdepasse) {
        this.id = id;
        this.login = login;
        this.motdepasse = motdepasse;
    }
    public Compte(int id, String login, String motdepasse, Set formateurs, Set apprenants) {
       this.id = id;
       this.login = login;
       this.motdepasse = motdepasse;
       this.formateurs = formateurs;
       this.apprenants = apprenants;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public Set getFormateurs() {
        return this.formateurs;
    }
    
    public void setFormateurs(Set formateurs) {
        this.formateurs = formateurs;
    }
    public Set getApprenants() {
        return this.apprenants;
    }
    
    public void setApprenants(Set apprenants) {
        this.apprenants = apprenants;
    }




}


