package entity;
// Generated 14 avr. 2019 16:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formation generated by hbm2java
 */
public class Formation  implements java.io.Serializable {


     private int idFormation;
     private String nom;
     private int duree;
     private String discipline;
     private String nbmodules;
     private String description;
     private Set apprenants = new HashSet(0);
     private Set formateurs = new HashSet(0);
     private Set modules = new HashSet(0);

    public Formation() {
    }

	
    public Formation(int idFormation, String nom, int duree, String nbmodules, String description) {
        this.idFormation = idFormation;
        this.nom = nom;
        this.duree = duree;
        this.nbmodules = nbmodules;
        this.description = description;
    }
    public Formation(int idFormation, String nom, int duree, String discipline, String nbmodules, String description, Set apprenants, Set formateurs, Set modules) {
       this.idFormation = idFormation;
       this.nom = nom;
       this.duree = duree;
       this.discipline = discipline;
       this.nbmodules = nbmodules;
       this.description = description;
       this.apprenants = apprenants;
       this.formateurs = formateurs;
       this.modules = modules;
    }
   
    public int getIdFormation() {
        return this.idFormation;
    }
    
    public void setIdFormation(int idFormation) {
        this.idFormation = idFormation;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getDuree() {
        return this.duree;
    }
    
    public void setDuree(int duree) {
        this.duree = duree;
    }
    public String getDiscipline() {
        return this.discipline;
    }
    
    public void setDiscipline(String discipline) {
        this.discipline = discipline;
    }
    public String getNbmodules() {
        return this.nbmodules;
    }
    
    public void setNbmodules(String nbmodules) {
        this.nbmodules = nbmodules;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getApprenants() {
        return this.apprenants;
    }
    
    public void setApprenants(Set apprenants) {
        this.apprenants = apprenants;
    }
    public Set getFormateurs() {
        return this.formateurs;
    }
    
    public void setFormateurs(Set formateurs) {
        this.formateurs = formateurs;
    }
    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }




}


