package entity;
// Generated 14 avr. 2019 16:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private int id;
     private Formateur formateur;
     private Formation formation;
     private String nom;
     private String description;
     private Set chapitres = new HashSet(0);
     private Set apprenants = new HashSet(0);
     private Set ressources = new HashSet(0);

    public Module() {
    }

	
    public Module(int id, Formateur formateur, Formation formation, String nom, String description) {
        this.id = id;
        this.formateur = formateur;
        this.formation = formation;
        this.nom = nom;
        this.description = description;
    }
    public Module(int id, Formateur formateur, Formation formation, String nom, String description, Set chapitres, Set apprenants, Set ressources) {
       this.id = id;
       this.formateur = formateur;
       this.formation = formation;
       this.nom = nom;
       this.description = description;
       this.chapitres = chapitres;
       this.apprenants = apprenants;
       this.ressources = ressources;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Formateur getFormateur() {
        return this.formateur;
    }
    
    public void setFormateur(Formateur formateur) {
        this.formateur = formateur;
    }
    public Formation getFormation() {
        return this.formation;
    }
    
    public void setFormation(Formation formation) {
        this.formation = formation;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getChapitres() {
        return this.chapitres;
    }
    
    public void setChapitres(Set chapitres) {
        this.chapitres = chapitres;
    }
    public Set getApprenants() {
        return this.apprenants;
    }
    
    public void setApprenants(Set apprenants) {
        this.apprenants = apprenants;
    }
    public Set getRessources() {
        return this.ressources;
    }
    
    public void setRessources(Set ressources) {
        this.ressources = ressources;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Module other = (Module) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
  
}





